/**
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext.ui.contentassist;

import org.eclipse.oclinecore.tutorial.xtext.ui.contentassist.AbstractLibraryDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LibraryDslProposalProvider extends AbstractLibraryDslProposalProvider {
}
