/*
* generated by Xtext
*/
package org.eclipse.oclinecore.tutorial.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LibraryDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.oclinecore.tutorial.xtext.ui.internal.LibraryDslActivator.getInstance().getInjector("org.eclipse.oclinecore.tutorial.xtext.LibraryDsl");
	}
	
}
