/**
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext.validation;

import org.eclipse.oclinecore.tutorial.xtext.validation.AbstractLibraryDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class LibraryDslValidator extends AbstractLibraryDslValidator {
}
