/**
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext.serializer;

import org.eclipse.oclinecore.tutorial.xtext.serializer.AbstractLibraryDslSemanticSequencer;

@SuppressWarnings("all")
public class LibraryDslSemanticSequencer extends AbstractLibraryDslSemanticSequencer {
}
