/**
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext.serializer;

import org.eclipse.oclinecore.tutorial.xtext.serializer.AbstractLibraryDslSyntacticSequencer;

@SuppressWarnings("all")
public class LibraryDslSyntacticSequencer extends AbstractLibraryDslSyntacticSequencer {
}
