/*
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LibraryDslUiModule extends org.eclipse.oclinecore.tutorial.xtext.ui.AbstractLibraryDslUiModule {
	public LibraryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
