/*
* generated by Xtext
*/
package org.eclipse.oclinecore.tutorial.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LibraryDslStandaloneSetup extends LibraryDslStandaloneSetupGenerated{

	public static void doSetup() {
		new LibraryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

