/*
 * generated by Xtext
 */
package org.eclipse.oclinecore.tutorial.xtext;

import com.google.inject.Binder;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LibraryDslRuntimeModule extends org.eclipse.oclinecore.tutorial.xtext.AbstractLibraryDslRuntimeModule {
	
	//http://www.eclipse.org/forums/index.php/mv/msg/209565/672370/#msg_672370
	@Override
	public void configure(Binder binder) {
		super.configure(binder);

		binder.bindConstant().annotatedWith(Names.named(org.eclipse.xtext.validation.CompositeEValidator.USE_EOBJECT_VALIDATOR)).to(false);
	}
}
