/*
* generated by Xtext
*/
package org.eclipse.oclinecore.tutorial.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class LibraryDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class LibraryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Library");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLibraryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLibraryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBooksKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cBooksAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cBooksBookParserRuleCall_4_2_0 = (RuleCall)cBooksAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cBooksAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cBooksBookParserRuleCall_4_3_1_0 = (RuleCall)cBooksAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLoansKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLoansAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLoansLoanParserRuleCall_5_2_0 = (RuleCall)cLoansAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLoansAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cLoansLoanParserRuleCall_5_3_1_0 = (RuleCall)cLoansAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMembersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cMembersAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cMembersMemberParserRuleCall_6_2_0 = (RuleCall)cMembersAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cMembersAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cMembersMemberParserRuleCall_6_3_1_0 = (RuleCall)cMembersAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Library:
		//	{Library} "Library" name=EString "{" ("books" "{" books+=Book ("," books+=Book)* "}")? ("loans" "{" loans+=Loan (","
		//	loans+=Loan)* "}")? ("members" "{" members+=Member ("," members+=Member)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Library} "Library" name=EString "{" ("books" "{" books+=Book ("," books+=Book)* "}")? ("loans" "{" loans+=Loan (","
		//loans+=Loan)* "}")? ("members" "{" members+=Member ("," members+=Member)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Library}
		public Action getLibraryAction_0() { return cLibraryAction_0; }

		//"Library"
		public Keyword getLibraryKeyword_1() { return cLibraryKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("books" "{" books+=Book ("," books+=Book)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"books"
		public Keyword getBooksKeyword_4_0() { return cBooksKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//books+=Book
		public Assignment getBooksAssignment_4_2() { return cBooksAssignment_4_2; }

		//Book
		public RuleCall getBooksBookParserRuleCall_4_2_0() { return cBooksBookParserRuleCall_4_2_0; }

		//("," books+=Book)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//books+=Book
		public Assignment getBooksAssignment_4_3_1() { return cBooksAssignment_4_3_1; }

		//Book
		public RuleCall getBooksBookParserRuleCall_4_3_1_0() { return cBooksBookParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("loans" "{" loans+=Loan ("," loans+=Loan)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"loans"
		public Keyword getLoansKeyword_5_0() { return cLoansKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//loans+=Loan
		public Assignment getLoansAssignment_5_2() { return cLoansAssignment_5_2; }

		//Loan
		public RuleCall getLoansLoanParserRuleCall_5_2_0() { return cLoansLoanParserRuleCall_5_2_0; }

		//("," loans+=Loan)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//loans+=Loan
		public Assignment getLoansAssignment_5_3_1() { return cLoansAssignment_5_3_1; }

		//Loan
		public RuleCall getLoansLoanParserRuleCall_5_3_1_0() { return cLoansLoanParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("members" "{" members+=Member ("," members+=Member)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"members"
		public Keyword getMembersKeyword_6_0() { return cMembersKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//members+=Member
		public Assignment getMembersAssignment_6_2() { return cMembersAssignment_6_2; }

		//Member
		public RuleCall getMembersMemberParserRuleCall_6_2_0() { return cMembersMemberParserRuleCall_6_2_0; }

		//("," members+=Member)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//members+=Member
		public Assignment getMembersAssignment_6_3_1() { return cMembersAssignment_6_3_1; }

		//Member
		public RuleCall getMembersMemberParserRuleCall_6_3_1_0() { return cMembersMemberParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class BookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Book");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCopiesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCopiesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCopiesEBigIntegerParserRuleCall_4_0 = (RuleCall)cCopiesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Book:
		//	"Book" name=EString "{" "copies" copies=EBigInteger "}";
		public ParserRule getRule() { return rule; }

		//"Book" name=EString "{" "copies" copies=EBigInteger "}"
		public Group getGroup() { return cGroup; }

		//"Book"
		public Keyword getBookKeyword_0() { return cBookKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"copies"
		public Keyword getCopiesKeyword_3() { return cCopiesKeyword_3; }

		//copies=EBigInteger
		public Assignment getCopiesAssignment_4() { return cCopiesAssignment_4; }

		//EBigInteger
		public RuleCall getCopiesEBigIntegerParserRuleCall_4_0() { return cCopiesEBigIntegerParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class LoanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Loan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoanKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBookKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBookAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cBookBookCrossReference_3_0 = (CrossReference)cBookAssignment_3.eContents().get(0);
		private final RuleCall cBookBookEStringParserRuleCall_3_0_1 = (RuleCall)cBookBookCrossReference_3_0.eContents().get(1);
		private final Keyword cMemberKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cMemberAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cMemberMemberCrossReference_5_0 = (CrossReference)cMemberAssignment_5.eContents().get(0);
		private final RuleCall cMemberMemberEStringParserRuleCall_5_0_1 = (RuleCall)cMemberMemberCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loan:
		//	"Loan" "{" "book" book=[Book|EString] "member" member=[Member|EString] "}";
		public ParserRule getRule() { return rule; }

		//"Loan" "{" "book" book=[Book|EString] "member" member=[Member|EString] "}"
		public Group getGroup() { return cGroup; }

		//"Loan"
		public Keyword getLoanKeyword_0() { return cLoanKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"book"
		public Keyword getBookKeyword_2() { return cBookKeyword_2; }

		//book=[Book|EString]
		public Assignment getBookAssignment_3() { return cBookAssignment_3; }

		//[Book|EString]
		public CrossReference getBookBookCrossReference_3_0() { return cBookBookCrossReference_3_0; }

		//EString
		public RuleCall getBookBookEStringParserRuleCall_3_0_1() { return cBookBookEStringParserRuleCall_3_0_1; }

		//"member"
		public Keyword getMemberKeyword_4() { return cMemberKeyword_4; }

		//member=[Member|EString]
		public Assignment getMemberAssignment_5() { return cMemberAssignment_5; }

		//[Member|EString]
		public CrossReference getMemberMemberCrossReference_5_0() { return cMemberMemberCrossReference_5_0; }

		//EString
		public RuleCall getMemberMemberEStringParserRuleCall_5_0_1() { return cMemberMemberEStringParserRuleCall_5_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Member");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMemberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMemberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Member:
		//	{Member} "Member" name=EString;
		public ParserRule getRule() { return rule; }

		//{Member} "Member" name=EString
		public Group getGroup() { return cGroup; }

		//{Member}
		public Action getMemberAction_0() { return cMemberAction_0; }

		//"Member"
		public Keyword getMemberKeyword_1() { return cMemberKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}

	public class EBigIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBigInteger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EBigInteger returns ecore::EBigInteger:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private LibraryElements pLibrary;
	private EStringElements pEString;
	private BookElements pBook;
	private LoanElements pLoan;
	private MemberElements pMember;
	private EBigIntegerElements pEBigInteger;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public LibraryDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.oclinecore.tutorial.xtext.LibraryDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Library:
	//	{Library} "Library" name=EString "{" ("books" "{" books+=Book ("," books+=Book)* "}")? ("loans" "{" loans+=Loan (","
	//	loans+=Loan)* "}")? ("members" "{" members+=Member ("," members+=Member)* "}")? "}";
	public LibraryElements getLibraryAccess() {
		return (pLibrary != null) ? pLibrary : (pLibrary = new LibraryElements());
	}
	
	public ParserRule getLibraryRule() {
		return getLibraryAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Book:
	//	"Book" name=EString "{" "copies" copies=EBigInteger "}";
	public BookElements getBookAccess() {
		return (pBook != null) ? pBook : (pBook = new BookElements());
	}
	
	public ParserRule getBookRule() {
		return getBookAccess().getRule();
	}

	//Loan:
	//	"Loan" "{" "book" book=[Book|EString] "member" member=[Member|EString] "}";
	public LoanElements getLoanAccess() {
		return (pLoan != null) ? pLoan : (pLoan = new LoanElements());
	}
	
	public ParserRule getLoanRule() {
		return getLoanAccess().getRule();
	}

	//Member:
	//	{Member} "Member" name=EString;
	public MemberElements getMemberAccess() {
		return (pMember != null) ? pMember : (pMember = new MemberElements());
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}

	//EBigInteger returns ecore::EBigInteger:
	//	"-"? INT;
	public EBigIntegerElements getEBigIntegerAccess() {
		return (pEBigInteger != null) ? pEBigInteger : (pEBigInteger = new EBigIntegerElements());
	}
	
	public ParserRule getEBigIntegerRule() {
		return getEBigIntegerAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
