/*
* generated by Xtext
*/
package org.eclipse.oclinecore.tutorial.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.oclinecore.tutorial.xtext.services.LibraryDslGrammarAccess;

public class LibraryDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LibraryDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.oclinecore.tutorial.xtext.parser.antlr.internal.InternalLibraryDslParser createParser(XtextTokenStream stream) {
		return new org.eclipse.oclinecore.tutorial.xtext.parser.antlr.internal.InternalLibraryDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Library";
	}
	
	public LibraryDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LibraryDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
