/*
* generated by Xtext
*/
package org.eclipse.oclinecore.tutorial.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LibraryDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/oclinecore/tutorial/xtext/parser/antlr/internal/InternalLibraryDsl.tokens");
	}
}
